/**
 * 
 *   Copyright (C) 2008 Lasse Parikka
 *
 *   This program is free software; you can redistribute it and/or modify it under the terms of
 *   the GNU General Public License as published by the Free Software Foundation; either version 2
 *   of the License, or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 *   without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 *   See the GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License along with this program;
 *   if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 *   MA 02111-1307 USA
 *
 *   Also add information on how to contact you by electronic and paper mail.
 *
 */
package checker.gui.cvs;

import java.awt.Component;
import java.awt.Font;
import java.util.regex.Pattern;

import javax.swing.JFileChooser;
import org.jdesktop.swingworker.SwingWorker;

import checker.gui.svn.CheckoutEvent;
import checker.gui.svn.SVNDirSelector;
import checker.repository.CVSRepository;
import checker.localization.Locale;


/**
 * Shows CVS checkout wizard, performs the checkout.
 */
public class CVSCheckoutWizard extends javax.swing.JDialog {
  
   
    private CVSRepository repository;
    
    private OpenRepositoryTask openTask;

	private CVSModuleSelector moduleTree;
	
	//local path to checked folder.
	private String checkedFolder;
	
	/* Localization */
	Locale loc = new Locale();

	
	
	/** Creates new form SVNConnection */
    public CVSCheckoutWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        step1 = new javax.swing.JPanel();
        finishButton1 = new javax.swing.JButton();
        cancelButton1 = new javax.swing.JButton();
        helpButton1 = new javax.swing.JButton();
        nextButton1 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        svnUrlBox = new javax.swing.JComboBox();
        stopButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        connectionInfoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        step2 = new javax.swing.JPanel();
        finishButton2 = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();
        helpButton2 = new javax.swing.JButton();
        nextButton2 = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        usernameLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        revisionField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        folderPathField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        connectionInfoLabel2 = new javax.swing.JLabel();
        usernameLabel2 = new javax.swing.JLabel();
        folderPathField1 = new javax.swing.JTextField();
        browseButton1 = new javax.swing.JButton();
        sampleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());
        jButton1.setEnabled(false);
        step1.setName("step1"); // NOI18N
        
        sampleLabel.setFont(new java.awt.Font("sansserif", Font.PLAIN, 11));
        sampleLabel.setText("( :[access_method]:[username]@[hostname]:/[repository path] )");
        
        finishButton1.setText(loc.lc("Finish")); // NOI18N
        finishButton1.setEnabled(false);
        finishButton1.setName("finishButton1"); // NOI18N
        finishButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButton1ActionPerformed(evt);
            }
        });

        cancelButton1.setText(loc.lc("Cancel")); // NOI18N
        cancelButton1.setName("cancelButton1"); // NOI18N

        helpButton1.setText(loc.lc("Help")); // NOI18N
        helpButton1.setEnabled(false);
        helpButton1.setMaximumSize(new java.awt.Dimension(72, 25));
        helpButton1.setMinimumSize(new java.awt.Dimension(72, 25));
        helpButton1.setName("helpButton1"); // NOI18N
        helpButton1.setPreferredSize(new java.awt.Dimension(72, 25));

        nextButton1.setText(loc.lc("Next")); // NOI18N
        nextButton1.setMaximumSize(new java.awt.Dimension(72, 25));
        nextButton1.setMinimumSize(new java.awt.Dimension(72, 25));
        nextButton1.setName("nextButton1"); // NOI18N
        nextButton1.setPreferredSize(new java.awt.Dimension(72, 25));
        nextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton1ActionPerformed(evt);
            }
        });
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        backButton1.setText(loc.lc("Back")); // NOI18N
        backButton1.setEnabled(false);
        backButton1.setMaximumSize(new java.awt.Dimension(72, 25));
        backButton1.setMinimumSize(new java.awt.Dimension(72, 25));
        backButton1.setName("backButton1"); // NOI18N
        backButton1.setPreferredSize(new java.awt.Dimension(72, 25));

        jSeparator2.setName("jSeparator2"); // NOI18N

        jProgressBar2.setVisible(false);
        jProgressBar2.setName("jProgressBar2"); // NOI18N

        
       
        jLabel8.setText(loc.lc("CVS root")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("sansserif", Font.PLAIN, 11));
        jLabel9.setText(loc.lc("specify the location of CVS repository defined by CVS root.")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        jLabel10.setText(loc.lc("CVS root") + ":"); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        svnUrlBox.setEditable(true);
        svnUrlBox.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        //supported connection types. (ext should be added).
		svnUrlBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":pserver:"  }));
		svnUrlBox.setName("typesBox");

        stopButton.setText(loc.lc("Stop")); // NOI18N
        stopButton.setVisible(false);
        stopButton.setName("stopButton"); // NOI18N
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        jSeparator3.setName("jSeparator3"); // NOI18N

        jLabel11.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        jLabel11.setText(loc.lc("Password") + ":"); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jPasswordField.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        jPasswordField.setText(""); // NOI18N
        jPasswordField.setName("jPasswordField"); // NOI18N

        connectionInfoLabel.setFont(new java.awt.Font("sansserif", Font.PLAIN, 11));
        connectionInfoLabel.setText(loc.lc("Authentication in progress...")); // NOI18N
        connectionInfoLabel.setVisible(false);
        connectionInfoLabel.setName("connectionInfoLabel"); // NOI18N

        jButton1.setText(loc.lc("Edit")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout step1Layout = new org.jdesktop.layout.GroupLayout(step1);
        step1.setLayout(step1Layout);
        step1Layout.setHorizontalGroup(
            step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(step1Layout.createSequentialGroup()
                .addContainerGap()
                .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(step1Layout.createSequentialGroup()
                        .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(step1Layout.createSequentialGroup()
                                .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel9)
                                    .add(step1Layout.createSequentialGroup()
                                        .add(jLabel10)
                                        .add(25, 25, 25)
                                        .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(sampleLabel)
                                            .add(svnUrlBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 384, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE))
                            .add(step1Layout.createSequentialGroup()
                                .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(connectionInfoLabel)
                                    .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(stopButton)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel8)
                    .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 442, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, step1Layout.createSequentialGroup()
                        .add(backButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(nextButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(finishButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(helpButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .add(step1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel11)
                .add(21, 21, 21)
                .add(jPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        step1Layout.setVerticalGroup(
            step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(step1Layout.createSequentialGroup()
                .addContainerGap()
                .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(step1Layout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(svnUrlBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sampleLabel)
                        .add(8, 8, 8)
                        .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 129, Short.MAX_VALUE)
                        .add(connectionInfoLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jProgressBar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(stopButton))
                .add(16, 16, 16)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(step1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(helpButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cancelButton1)
                    .add(finishButton1)
                    .add(nextButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(backButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(step1, "step1card");

        getContentPane().add(step1, "step1card");

        step2.setName("step2"); // NOI18N

        finishButton2.setText(loc.lc("Finish")); // NOI18N
        finishButton2.setName("finishButton2"); // NOI18N
        finishButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButton2ActionPerformed(evt);
            }
        });

        cancelButton2.setText(loc.lc("Cancel")); // NOI18N
        cancelButton2.setName("cancelButton2"); // NOI18N

        helpButton2.setText(loc.lc("Help")); // NOI18N
        helpButton2.setEnabled(false);
        helpButton2.setMaximumSize(new java.awt.Dimension(72, 25));
        helpButton2.setMinimumSize(new java.awt.Dimension(72, 25));
        helpButton2.setName("helpButton2"); // NOI18N
        helpButton2.setPreferredSize(new java.awt.Dimension(72, 25));

        nextButton2.setText(loc.lc("Next")); // NOI18N
        nextButton2.setEnabled(false);
        nextButton2.setMaximumSize(new java.awt.Dimension(72, 25));
        nextButton2.setMinimumSize(new java.awt.Dimension(72, 25));
        nextButton2.setName("nextButton2"); // NOI18N
        nextButton2.setPreferredSize(new java.awt.Dimension(72, 25));
        nextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton2ActionPerformed(evt);
            }
        });

        backButton2.setText(loc.lc("Back")); // NOI18N
        backButton2.setMaximumSize(new java.awt.Dimension(72, 25));
        backButton2.setMinimumSize(new java.awt.Dimension(72, 25));
        backButton2.setName("backButton2"); // NOI18N
        backButton2.setPreferredSize(new java.awt.Dimension(72, 25));
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        jSeparator5.setName("jSeparator5"); // NOI18N

        
        jLabel16.setText(loc.lc("Module to checkout")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

       
        jLabel17.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        jLabel17.setText(loc.lc("Specify the CVS module and branch  to checkout from CVS repository.")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

       
        jLabel18.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        jLabel18.setText(loc.lc("Module") + ":"); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jSeparator7.setName("jSeparator7"); // NOI18N

       
        usernameLabel1.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        usernameLabel1.setText(loc.lc("Branch") + ":"); // NOI18N
        usernameLabel1.setName("usernameLabel1"); // NOI18N

        jLabel20.setFont(new java.awt.Font("sansserif", Font.PLAIN, 11));
        jLabel20.setText(loc.lc("(empty means all modules)")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        revisionField.setText(""); // NOI18N
        revisionField.setName("revisionField"); // NOI18N
        revisionField.setEditable(false);
        searchButton.setText(loc.lc("Browse...")); // NOI18N
        searchButton.setEnabled(false);
        searchButton.setName("searchButton"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        
        folderPathField.setText(""); // NOI18N
        folderPathField.setName("folderPathField"); // NOI18N

        browseButton.setText(loc.lc("Browse...")); // NOI18N
        browseButton.setName("browseButton"); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        connectionInfoLabel2.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        connectionInfoLabel2.setText(loc.lc("Specify the local folder to checkout module into.")); // NOI18N
        connectionInfoLabel2.setName("connectionInfoLabel2"); // NOI18N

        usernameLabel2.setFont(new java.awt.Font("sansserif", Font.PLAIN, 12));
        usernameLabel2.setText(loc.lc("Local folder") + ":"); // NOI18N
        usernameLabel2.setName("usernameLabel2"); // NOI18N

        folderPathField1.setName("folderPathField1"); // NOI18N
        folderPathField1.setText(System.getProperty("user.home"));
        browseButton1.setText(loc.lc("Browse...")); // NOI18N
        browseButton1.setName("browseButton1"); // NOI18N
        browseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout step2Layout = new org.jdesktop.layout.GroupLayout(step2);
        step2.setLayout(step2Layout);
        step2Layout.setHorizontalGroup(
            step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, step2Layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .add(backButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nextButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(finishButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cancelButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(helpButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jSeparator5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, step2Layout.createSequentialGroup()
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(step2Layout.createSequentialGroup()
                        .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(step2Layout.createSequentialGroup()
                                .add(11, 11, 11)
                                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(step2Layout.createSequentialGroup()
                                        .add(usernameLabel2)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(folderPathField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                                    .add(connectionInfoLabel2)
                                    .add(jLabel17)
                                    .add(step2Layout.createSequentialGroup()
                                        .add(jLabel18)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(folderPathField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(step2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 454, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(step2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel16)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(step2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(usernameLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 226, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(revisionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 394, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(8, 8, 8)))
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(searchButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, browseButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(step2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(browseButton1)))
                .addContainerGap())
        );
        step2Layout.setVerticalGroup(
            step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, step2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(browseButton)
                    .add(folderPathField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(jLabel20)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel1)
                    .add(searchButton)
                    .add(revisionField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(56, 56, 56)
                .add(connectionInfoLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel2)
                    .add(browseButton1)
                    .add(folderPathField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 68, Short.MAX_VALUE)
                .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(step2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(helpButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cancelButton2)
                    .add(finishButton2)
                    .add(nextButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(backButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );


        getContentPane().add(step2, "step2card");

        pack();
    }// </editor-fold>

private void finishButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
    
}  

/**
 * checkout a module from the repository.
 */
private void finishButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	
	CVSCheckoutEvent dial = new CVSCheckoutEvent(this, null, true, repository,
			folderPathField.getText(), folderPathField1.getText());
	
	
	Pattern p = Pattern.compile("/");
	String[] items = p.split(folderPathField.getText());
	String moduleName = items[0];
	
	if (!dial.isCancelled()) {
		checkedFolder = folderPathField1.getText() + System.getProperty("file.separator") + 
			moduleName;
	}
	else 
		checkedFolder = null;
	
	this.setVisible(false);
	
}                                             

private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
// TODO add your handling code here:
}

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
	this.setVisible(false);
}

private void nextButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
	 
	  repository = new CVSRepository();
	  String password = new String(jPasswordField.getPassword());
	  openTask = new OpenRepositoryTask((String) svnUrlBox.getSelectedItem(),
			  password);
	  openTask.execute();
	 
}    

private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                            

    java.awt.CardLayout cl = (java.awt.CardLayout)
            (getContentPane().getLayout());
            cl.show(getContentPane(), "step1card");
}                                           

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

/**
 * browse local filesystem.
 */
private void browseButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	
	JFileChooser chooser = new JFileChooser();
	chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	chooser.setMultiSelectionEnabled(false);
	int returnVal = chooser.showOpenDialog(this);
	if(returnVal == JFileChooser.APPROVE_OPTION) {

		folderPathField1.setText(chooser.getSelectedFile().
				getPath());
	}
	
}

/**
 * shows module selector window
 */
private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {
	
	moduleTree = new CVSModuleSelector(null, true,
			repository);
	moduleTree.setLocationRelativeTo(this);
	moduleTree.setVisible(true);
	folderPathField.setText(moduleTree.getSelectedModulePath());
	
}



/**
 * opening was cancelled.
 */
private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {
	openTask.cancel(true);
	
}

/**
 * Browse repository branches
 */
private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
 
	
}

public String getCheckedFolderPath() {
	return checkedFolder;
}

/**
 * a worker thread that opens a connection to the CVS
 * repository.
 */
class OpenRepositoryTask extends SwingWorker<Void, Void> {

	
	private int exception = 0;
	private String cvsRoot;
	private String password;

	public OpenRepositoryTask(String root, 
			String pass) {
		cvsRoot = root;
		password = pass;
	}

	
	protected Void doInBackground() {
		jProgressBar2.setVisible(true);
		jProgressBar2.setIndeterminate(true);
		stopButton.setVisible(true);
		connectionInfoLabel.setVisible(true);
		try {
			repository.setParameters(cvsRoot, password);
			repository.openConnection();
		} catch (Exception e) {
			exception  = 1;
		}
		
		return null;
	}

	protected void done() {

		jProgressBar2.setVisible(false);
		jProgressBar2.setIndeterminate(false);
		stopButton.setVisible(false);
		connectionInfoLabel.setVisible(false);
		nextButton1.setEnabled(true);
		//exception occured. show error dialog to the user.
		if (exception == 1 || isCancelled()) {

			if (isCancelled()) {
				//svnExceptionMessage = "Verification stopped by user";
			}
			javax.swing.JOptionPane.showMessageDialog(step1,
					loc.lc("please check username, password and repository"),
					loc.lc("Error") ,
					javax.swing.JOptionPane.ERROR_MESSAGE);
		}
		else {
			backButton1.setEnabled(true);
			
			java.awt.CardLayout cl = (java.awt.CardLayout)
			(getContentPane().getLayout());
			cl.show(getContentPane(), "step2card");
		}
	}

}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CVSCheckoutWizard dialog = new CVSCheckoutWizard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseButton1;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JLabel connectionInfoLabel;
    private javax.swing.JLabel connectionInfoLabel2;
    private javax.swing.JButton finishButton1;
    private javax.swing.JButton finishButton2;
    private javax.swing.JTextField folderPathField;
    private javax.swing.JTextField folderPathField1;
    private javax.swing.JButton helpButton1;
    private javax.swing.JButton helpButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton nextButton1;
    private javax.swing.JButton nextButton2;
    private javax.swing.JTextField revisionField;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel step1;
    private javax.swing.JPanel step2;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox svnUrlBox;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JLabel usernameLabel2;
    private javax.swing.JLabel sampleLabel;
    // End of variables declaration

}

