/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteLicense.java
 *
 * Created on 20.2.2009, 0:58:52
 */

package checker.gui.license;

import checker.gui.combo.LicensesBoxModel;
import checker.gui.combo.LicensesBoxRenderer;
import checker.license.License;
import checker.license.LicenseEditor;
import checker.localization.Locale;
import javax.swing.JOptionPane;

/**
 * Dialog for deleting licenses
 *
 * @author ekurkela
 */
public class DeleteLicense extends javax.swing.JDialog {
    private Locale loc = new Locale();

    /** Creates new form DeleteLicense */
    public DeleteLicense(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // set model and renderer for license selection combo box
        selectLicenseComboBox.setModel(new LicensesBoxModel(true));
        selectLicenseComboBox.setRenderer(new LicensesBoxRenderer());
        
        //disable "delete" button if no licenses available
        if(selectLicenseComboBox.getModel().getSize() < 1) {
     	   deleteButton.setEnabled(false);
        }
        else {
     	   deleteButton.setEnabled(true);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        selectLicenseLabel = new javax.swing.JLabel();
        selectLicenseComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(loc.lc("Delete license"));

        cancelButton.setText(loc.lc("Cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setText(loc.lc("Delete license"));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        selectLicenseLabel.setText(loc.lc("Select license"));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(deleteButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(selectLicenseLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(selectLicenseComboBox, 0, 276, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelButton, deleteButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(selectLicenseLabel)
                    .add(selectLicenseComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(deleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
}//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        LicenseEditor le = new LicenseEditor();
        int res = le.deleteLicense(((License)selectLicenseComboBox.getSelectedItem()).getId());
        if (res == 0) {
            JOptionPane.showMessageDialog(this,
                    "License deleted",
                    "OSLC", JOptionPane.INFORMATION_MESSAGE);
            //System.out.println(loc.lc("License deleted"));
        } else {
            String msg = "Error: ";
            if (res == 1) {
                msg += "file(s) do not exist";
            } else if (res == 2) {
                msg += "file(s) is(are) write protected";
            } else if (res == 3) {
                msg += "meta file not deleted (fatal error)";
            } else if (res == 4) {
                msg += "txt file not deleted (fatal error)";
            }
            JOptionPane.showMessageDialog(this,
                    msg,
                    loc.lc("Error"), JOptionPane.ERROR_MESSAGE);
            //System.out.println(loc.lc(msg));
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeleteLicense dialog = new DeleteLicense(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox selectLicenseComboBox;
    private javax.swing.JLabel selectLicenseLabel;
    // End of variables declaration//GEN-END:variables

}
