/*
 * DownloadDatabase.java
 *
 * Created on 6.2.2009, 12:09:34
 */

package checker.gui.license;

import checker.Downloader;
import checker.localization.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author ekurkela
 *
 * TBD: improve error handling
 */
public class DownloadDatabase extends javax.swing.JDialog {
    Locale loc = new Locale();

    /** Creates new form DownloadDatabase */
    public DownloadDatabase(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        URLLabel = new javax.swing.JLabel();
        downloadButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        URLComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(loc.lc("Download license database"));
        setBackground(java.awt.Color.white);

        URLLabel.setText("URL");

        downloadButton.setText(loc.lc("Download"));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(loc.lc("Cancel"));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setText(loc.lc("Status")+": "+loc.lc("idle"));

        URLComboBox.setEditable(true);
        URLComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "http://download.forge.objectweb.org/oslcv3/database.zip", "" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(downloadButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(URLLabel)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(249, 249, 249)
                                .add(statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(URLComboBox, 0, 398, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {cancelButton, downloadButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(URLLabel)
                    .add(URLComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusLabel)
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(downloadButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Downloads and unzips license database */
    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        Downloader dl = new Downloader();

        // download
        statusLabel.setText(loc.lc("Status")+": "+loc.lc("downloading database"));
        dl.download_file(URLComboBox.getModel().getSelectedItem().toString());

        // unzip & give feedback
       statusLabel.setText(loc.lc("Status")+": "+loc.lc("unpacking files"));
       if(dl.unzip()) {
            JOptionPane.showMessageDialog(this,
            		loc.lc("License database downloaded"),
                    loc.lc("Done"), JOptionPane.INFORMATION_MESSAGE);
       }
       else {
            JOptionPane.showMessageDialog(this,
            		loc.lc("License database could not be downloaded"),
                    loc.lc("Error"), JOptionPane.ERROR_MESSAGE);
       }

        statusLabel.setText(loc.lc("Status")+": "+loc.lc("idle"));
        dispose();
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DownloadDatabase dialog = new DownloadDatabase(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox URLComboBox;
    private javax.swing.JLabel URLLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

}
